[package]
name = "rtext"
version = "0.1.1"
edition = "2021"

[dependencies]
anyhow = "1.0.80"
bytesize = "1.3.0"
clap = { version = "4.5.1", features = ["derive"] }
colored = "2.1.0"
num-format = "0.4.4"
random_word = { version = "0.4.3", features = ["en"] }
