[package]
name = "rtext"
version = "0.1.1"
edition = "2021"

[dependencies]
anyhow = "1.0.80"
clap = { version = "4.5.1", features = ["derive"] }
random_word = { version = "0.4.3", features = ["en"] }
